version: 1.4.0.{build}
skip_tags: true
os:
  - Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  - ps: .\Build.ps1
after_test:
  -ps: .\AfterTest.ps1
artifacts:
  - path: '**\*.nupkg'
    name: Lanem
deploy:
  provider: NuGet
  api_key:
    secure: +XDgIu4Tmln7LKedNmQgMFnyKTxxuCKFRK3V5oKEfwZiakPXRd5C7OueEGBL50oh
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
