version: 3.0.0.{build}
os:
  - Visual Studio 2015
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build_script:
  - ps: .\Build.ps1
after_test:
  - ps: .\AfterTest.ps1
artifacts:
  - path: 'Lanem.*.nupkg'
    name: Lanem
nuget:
  account_feed: false
  project_feed: false
deploy:
  provider: NuGet
  api_key:
    secure: +XDgIu4Tmln7LKedNmQgMFnyKTxxuCKFRK3V5oKEfwZiakPXRd5C7OueEGBL50oh
  skip_symbols: false
  artifact: /.*Lanem\..*\.nupkg/
  on:
    branch: master